### ISSUE TITLE
Your site was hacked

### ISSUE THREAD

**Issue by dsp2003** [kxproject/kX-Audio-driver-website#2]
Today I've opened the kxproject.com and discovered that all proper pages vanished from it, the text was displaying in Chinese and download section turned into a bunch of "1111". Please take measures as soon as possible.

**Comment by kxproject** [comment]
The domain name has expired. There was a notice of domain name expiration on the web page shown for several months, so that users could update their bookmarks. Github is the only official source for the driver binaries and the source code.

**Comment by dsp2003** [comment]
Not to judge you or anything, but from a logic standpoint allowing it to expire was a serious mistake, as the site was linked from tons of various forums and tech sites, which now direct users to an effectively malicious domain.

I don't know about your financial side, but you still could ask people to donate (a lot of us would, we're really grateful for your work to keep the E-MU cards alive, for all these years) and preserve the domain, while link it to a freely hosted site with a single redirect script, which would point users to the current GitHub repository.

Alas. :(

**Comment by kxproject** [comment]
Well, the notice has been there for approximately 10 months, and I got no messages, suggestions or any requests to keep the site running (and you only noticed the change after 3 months). Moreover, there have been no donations for years... So, I made a decision to cancel the domain name. In any case, there's github and the support forum. I will probably need to update the forum pages, so that they clearly state that github is now the only official driver source.
